#!/bin/bash

extensions=(
  "aaron-bond.better-comments"
  "anthropic.claude-code"
  "anysphere.remote-containers"
  "anysphere.remote-ssh"
  "bierner.emojisense"
  "bradlc.vscode-tailwindcss"
  "christian-kohler.npm-intellisense"
  "cocopon.iceberg-theme"
  "coenraads.bracket-pair-colorizer-2"
  "dbaeumer.vscode-eslint"
  "docker.docker"
  "eamodio.gitlens"
  "esbenp.prettier-vscode"
  "formulahendry.auto-rename-tag"
  "humao.rest-client"
  "johnpapa.vscode-peacock"
  "leonardssh.vscord"
  "luxcium.pop-n-lock-theme-vscode"
  "mikestead.dotenv"
  "monokai.theme-monokai-pro-vscode"
  "ms-azuretools.vscode-containers"
  "naumovs.color-highlight"
  "oderwat.indent-rainbow"
  "openai.chatgpt"
  "pascalx.sketchprompt"
  "pkief.material-icon-theme"
  "redhat.vscode-yaml"
  "rinckodev.constatic-theme"
  "rocketseat.theme-omni"
  "shopify.ruby-lsp"
  "steoates.autoimport"
  "streetsidesoftware.code-spell-checker"
  "streetsidesoftware.code-spell-checker-portuguese-brazilian"
  "usernamehw.errorlens"
  "vivaxy.vscode-conventional-commits"
  "vue.volar"
  "yoavbls.pretty-ts-errors"
)

for ext in "${extensions[@]}"; do
  echo "Instalando $ext..."
  cursor --install-extension "$ext" --force
done